## Numpy:Introduction

- NumPy is a Open Source Python package. It stands for **Numerical Python**. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

- NumPy is the fundamental package for scientific computing with Python , having following important functionalities: 
     - A powerful N-dimensional array object
     - A sophisticated (broadcasting) functions
     - Contains tools for integrating C/C++ and Fortran code
     - Have  useful  linear algebra, Fourier transform, and random number capabilities

## Why NuMpy?

- Mathematical and logical operations on **arrays**.

- Efficient storage and manipulation of **numerical arrays** is which is fundamental in  the process of  **data science**.

- NumPy arrays form the core of nearly the entire **ecosystem** of **data science** tools in Python,

In [4]:
!pip install numpy

In [5]:
import numpy as np

In [6]:
np.__version__

'1.26.4'

In [7]:
# We have lists in Python which serve the purpose of arrays,but their processing is slow.NumPy intends for providing an array object which is upto 50x faster as compared to handed-down Python lists

## In numpy,the array object is called ndarray.
## Arrays are oftentimes used in data science where resources and speed are essential.

In [8]:
## Arrays are homogeneous (same data type)

In [9]:
## It is a table of elements (typically numbers),all of the similar type, indexed by a tuple of positive integers

In [10]:
## Dimensions are named as axes in Numpy.The number of axes is rank

In [11]:
### NumPy's array class is know as ndarray.Even , it is known by the alias array

In [12]:
a =(1,2,3,4,5)

print(a)

(1, 2, 3, 4, 5)


In [13]:
type(a)


tuple

In [14]:
b= np.array(a)
print(b)

[1 2 3 4 5]


In [15]:
type(b)

numpy.ndarray

In [16]:
b.ndim # in order to find the dimsn

1

In [17]:
b.shape # no.of rows and no.columns

(5,)

In [18]:
b.size # total number of elements present in an array

5

In [19]:
b.dtype ## data type of my array

dtype('int32')

In [20]:
arr = np.array([[4,5,6],[7,8,9]])

print("Array elements are: ",arr)
print("Array is of type: ",type(arr))
print("No.of dimensions: ",arr.ndim)
print("Array shape: ",arr.shape)
print("Array size: ",arr.size)
print("Array stores elements of type: ",arr.dtype)

Array elements are:  [[4 5 6]
 [7 8 9]]
Array is of type:  <class 'numpy.ndarray'>
No.of dimensions:  2
Array shape:  (2, 3)
Array size:  6
Array stores elements of type:  int32


In [21]:
import numpy as arr

a =(1,2,3,4,5)
b =arr.array(a)
print (b)

[1 2 3 4 5]


In [22]:
#### Speed Comaprison numpy vs core python

In [23]:
import time as tm

size_1 = 10000000

def pure_python_version():
    start_time_pp =  tm.time() ## time of start of code execution
    list1 = range(size_1)
    list2 = range(size_1)
    sum_list=[list1[i]+list2[i] for i in range(len(list1))]
    end_time_pp =  tm.time()
    return end_time_pp - start_time_pp ## end time for execution (difference)

def numpy_version():
    start_time_np = tm.time()
    array1 = np.arange(size_1)
    array2 =  np.arange(size_1)
    sum_array = array1 + array2
    end_time_np = tm.time()
    return end_time_np - start_time_np ## end time for execution (difference)

python_time = pure_python_version()
numpy_time  = numpy_version()

print("pure python version=",python_time)
print("numpy =",numpy_time)

pure python version= 13.84116005897522
numpy = 0.19992589950561523


In [24]:
my_list=[2,3,4,6,7,8]

In [25]:
my_array=np.array(my_list)
my_array

array([2, 3, 4, 6, 7, 8])

In [26]:
array_2 = [[1,2,3],[4,5,6],[7,8,9]]
array_3= np.array(array_2)
array_3
type(array_3)

numpy.ndarray

In [27]:
array_3.ndim

2

In [28]:
array_3.shape

(3, 3)

In [29]:
a = np.array([1, 2, 3,7,5,1], ndmin = 2) 
print (a)
np.ndim(a)

[[1 2 3 7 5 1]]


2

In [30]:
a = np.array([1, 2, 3,7,5,1], ndmin = 3) 
print (a)
np.ndim(a)

[[[1 2 3 7 5 1]]]


3

In [31]:
a = np.array([1, 2, 3,7,5,1], ndmin = 10) 
print (a)
np.ndim(a)

[[[[[[[[[[1 2 3 7 5 1]]]]]]]]]]


10

In [32]:
a = np.array([1, 2, 3], dtype = complex) 
print (a)

[1.+0.j 2.+0.j 3.+0.j]


In [33]:
len(array_3) # total number of rows

3

In [34]:
array_3[2] #Indexing 3rd row

array([7, 8, 9])

In [35]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
array_3[0]

array([1, 2, 3])

In [40]:
array_3[2,0]

7

In [41]:
array_3[:,1] # Acessing Column

array([2, 5, 8])

In [43]:
array_3[:,2] # Acessing Column

array([3, 6, 9])

In [44]:
array_3[2:,:1] ## 3rd row onwards until 1st column

array([[7]])

In [45]:
array_3[2:,:2] ## 3rd row onwards until 2nd column

array([[7, 8]])

## Array Atrributes
Numpy Arrays are conveinent and fast as compared to Python Lists.
1.Shape(no of rows & columns)

In [46]:
array_3.shape #Rows*Column

(3, 3)

In [47]:
my_array.ndim #dimension of array

1

In [48]:
array_3.dtype

dtype('int32')

In [49]:
## Array Initilization

In [50]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.arange(1,10,3) #(start,end,space)

array([1, 4, 7])

In [52]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [53]:
np.zeros(9,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [55]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [57]:
np.eye(3,3) # Identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
np.array([4,5,6])

array([4, 5, 6])

In [60]:
np.linspace(0,4,100) # (start,end,no of values)

array([0.        , 0.04040404, 0.08080808, 0.12121212, 0.16161616,
       0.2020202 , 0.24242424, 0.28282828, 0.32323232, 0.36363636,
       0.4040404 , 0.44444444, 0.48484848, 0.52525253, 0.56565657,
       0.60606061, 0.64646465, 0.68686869, 0.72727273, 0.76767677,
       0.80808081, 0.84848485, 0.88888889, 0.92929293, 0.96969697,
       1.01010101, 1.05050505, 1.09090909, 1.13131313, 1.17171717,
       1.21212121, 1.25252525, 1.29292929, 1.33333333, 1.37373737,
       1.41414141, 1.45454545, 1.49494949, 1.53535354, 1.57575758,
       1.61616162, 1.65656566, 1.6969697 , 1.73737374, 1.77777778,
       1.81818182, 1.85858586, 1.8989899 , 1.93939394, 1.97979798,
       2.02020202, 2.06060606, 2.1010101 , 2.14141414, 2.18181818,
       2.22222222, 2.26262626, 2.3030303 , 2.34343434, 2.38383838,
       2.42424242, 2.46464646, 2.50505051, 2.54545455, 2.58585859,
       2.62626263, 2.66666667, 2.70707071, 2.74747475, 2.78787879,
       2.82828283, 2.86868687, 2.90909091, 2.94949495, 2.98989

In [61]:
np.linspace(1.23,4.7,10)

array([1.23      , 1.61555556, 2.00111111, 2.38666667, 2.77222222,
       3.15777778, 3.54333333, 3.92888889, 4.31444444, 4.7       ])

In [62]:
np.linspace(-2,2,10)

array([-2.        , -1.55555556, -1.11111111, -0.66666667, -0.22222222,
        0.22222222,  0.66666667,  1.11111111,  1.55555556,  2.        ])

In [63]:
np.random.rand(2)

array([0.94090184, 0.09582718])

In [64]:
np.random.rand(20)

array([0.11936861, 0.57495469, 0.07922548, 0.10416212, 0.79600226,
       0.20829169, 0.78885872, 0.62401116, 0.86113182, 0.22913036,
       0.63554958, 0.041723  , 0.55546221, 0.20255422, 0.15422416,
       0.0940268 , 0.31148904, 0.71483067, 0.64192367, 0.33041944])

In [65]:
np.random.rand(9)

array([0.33044174, 0.6764555 , 0.62650596, 0.15817686, 0.81734742,
       0.05936331, 0.03025177, 0.80425959, 0.89993815])

In [66]:
np.random.rand(2,2)

array([[0.17267961, 0.01702153],
       [0.61052051, 0.24942552]])

In [67]:
array_3.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [68]:
array_3.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [69]:
x=[[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,13]]
x=np.array(x)
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [70]:
x.min() ## overrall minimum

1

In [72]:
x.max()

13

In [73]:
x.sum()

112

In [75]:
x.mean()

7.0

In [76]:
x.min(axis=0) ## minimum value column wise

array([1, 2, 3, 4])

In [77]:
x.min(axis=1) 

array([ 1,  4,  7, 10])

In [79]:
x.max(axis=1) 

array([ 4,  7, 10, 13])

In [80]:
x.argmin() ## index of the minimum value 

0

In [81]:
x.argmax() ## index of the minimum value 

15

In [82]:
x.argmin(axis=0) #column wise

array([0, 0, 0, 0], dtype=int64)

In [83]:
x.argmin(axis=1) #column wise

array([0, 0, 0, 0], dtype=int64)

In [84]:
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [85]:
x.reshape(1,16) # 1D to 2D 

array([[ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10, 10, 11, 12, 13]])

In [86]:
x.reshape(2,8) # 1D to 2D 

array([[ 1,  2,  3,  4,  4,  5,  6,  7],
       [ 7,  8,  9, 10, 10, 11, 12, 13]])

In [87]:
x.reshape(6,2) # 1D to 2D 

ValueError: cannot reshape array of size 16 into shape (6,2)

In [88]:
x.flatten() #2D to 1D

array([ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10, 10, 11, 12, 13])

In [89]:
x.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12],
       [ 4,  7, 10, 13]])

In [ ]:
1
10
100
1000
10000

In [90]:
1/10000

0.0001

In [91]:
10/10000

0.001

In [92]:
9999/10000

0.9999

In [93]:
10000/10000

1.0

In [98]:
var =np.linspace(1,100, 1000000)

In [100]:
len(var)

1000000

In [101]:
list(var)

[1.0,
 1.000099000099,
 1.0001980001980002,
 1.0002970002970002,
 1.0003960003960004,
 1.0004950004950004,
 1.0005940005940006,
 1.0006930006930006,
 1.0007920007920008,
 1.0008910008910008,
 1.000990000990001,
 1.001089001089001,
 1.0011880011880012,
 1.0012870012870012,
 1.0013860013860014,
 1.0014850014850014,
 1.0015840015840016,
 1.0016830016830016,
 1.0017820017820018,
 1.0018810018810018,
 1.001980001980002,
 1.002079002079002,
 1.0021780021780022,
 1.0022770022770022,
 1.0023760023760024,
 1.0024750024750024,
 1.0025740025740026,
 1.0026730026730026,
 1.0027720027720028,
 1.0028710028710028,
 1.002970002970003,
 1.003069003069003,
 1.0031680031680033,
 1.0032670032670032,
 1.0033660033660035,
 1.0034650034650034,
 1.0035640035640037,
 1.0036630036630036,
 1.0037620037620039,
 1.0038610038610039,
 1.003960003960004,
 1.004059004059004,
 1.004158004158004,
 1.0042570042570043,
 1.0043560043560043,
 1.0044550044550045,
 1.0045540045540045,
 1.0046530046530047,
 1.0047520047520047,