### math

In [2]:
import numpy as np
A = np.array([ [4, 10, 11], [21, 22, 23], [31, 32, 33] ])
B = np.ones((3,3))
print(A)

[[ 4 10 11]
 [21 22 23]
 [31 32 33]]


In [3]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
print("Adding to arrays: ")
print(A + B)

Adding to arrays: 
[[ 5. 11. 12.]
 [22. 23. 24.]
 [32. 33. 34.]]


In [5]:
print("Substracting Two Arrays")
print(A-B)

Substracting Two Arrays
[[ 3.  9. 10.]
 [20. 21. 22.]
 [30. 31. 32.]]


In [6]:
print("\nMultiplying two arrays: ")
print(A * B)


Multiplying two arrays: 
[[ 4. 10. 11.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [7]:
print("Multiplying one Array with scalar")
print(3*A)

Multiplying one Array with scalar
[[12 30 33]
 [63 66 69]
 [93 96 99]]


In [8]:
print("Matrix Multiplication")
print(np.dot(A,B))

Matrix Multiplication
[[25. 25. 25.]
 [66. 66. 66.]
 [96. 96. 96.]]


In [9]:
np.sqrt(A)

array([[2.        , 3.16227766, 3.31662479],
       [4.58257569, 4.69041576, 4.79583152],
       [5.56776436, 5.65685425, 5.74456265]])

In [10]:
np.exp(A)

array([[5.45981500e+01, 2.20264658e+04, 5.98741417e+04],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09],
       [2.90488497e+13, 7.89629602e+13, 2.14643580e+14]])

In [11]:
np.log(A)

array([[1.38629436, 2.30258509, 2.39789527],
       [3.04452244, 3.09104245, 3.13549422],
       [3.4339872 , 3.4657359 , 3.49650756]])

In [12]:
a = np.array([0,30,45,60,90]) 
print(a)
print ('Sine of different angles:' )

[ 0 30 45 60 90]
Sine of different angles:


In [13]:
# Convert to radians by multiplying with pi/180 
print (np.sin(a*np.pi/180) )
print ("\n") 

[0.         0.5        0.70710678 0.8660254  1.        ]




In [14]:
print ('Cosine values for angles in array:')
print (np.cos(a*np.pi/180) )
print ("\n") 

Cosine values for angles in array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]




In [15]:
print ('Tangent values for given angles:' )
print (np.tan(a*np.pi/180) )

Tangent values for given angles:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [16]:
a=np.array([[11.667,23.662],[33.21,45.887]])
print (np.around(a)) 

[[12. 24.]
 [33. 46.]]


In [17]:
print (np.around(a, decimals = 1))

[[11.7 23.7]
 [33.2 45.9]]


In [18]:
print (np.around(a, decimals = 2))

[[11.67 23.66]
 [33.21 45.89]]


In [19]:
A.sum() ## SUM OF ALL THE DATA 

187

In [20]:
A.sum(axis=0) ## row wise

array([56, 64, 67])

In [21]:
A.sum(axis=1) ## Column wise

array([25, 66, 96])

In [22]:
A.mean()

20.77777777777778

In [23]:
np.std(A)

9.88576729757121

In [24]:
np.std(A,axis=0)

array([11.14550233,  8.99382504,  8.99382504])

In [25]:
np.median(A)

22.0

In [26]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [27]:
np.mod(A,23)   #modulus

array([[ 4, 10, 11],
       [21, 22,  0],
       [ 8,  9, 10]], dtype=int32)

In [28]:
np.var(A)    #Variance

97.72839506172839

#### Binary Universal Functions

In [29]:
A=[[1,2,3],[3,4,5]]
B=[[3,3,4],[1,2,0]]
a=np.array(A)
b=np.array(B)
np.greater_equal(a,b)

array([[False, False, False],
       [ True,  True,  True]])

In [30]:
A

[[1, 2, 3], [3, 4, 5]]

In [31]:
B

[[3, 3, 4], [1, 2, 0]]

In [32]:
np.greater_equal(b,a)

array([[ True,  True,  True],
       [False, False, False]])

In [33]:
np.less(a,b)

array([[ True,  True,  True],
       [False, False, False]])

### Subsetting array

In [34]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [37]:
subset1 = a[:,1] = 2  ## sub set element before postion 0 to value 1

In [38]:
a

array([[1, 2, 3],
       [1, 2, 5]])

### Concatenating Arrays

In [42]:
np.concatenate([a,b])

array([[1, 2, 3],
       [1, 2, 5],
       [3, 3, 4],
       [1, 2, 0]])

In [39]:
np.concatenate([a,b],axis=1)

array([[1, 2, 3, 3, 3, 4],
       [1, 2, 5, 1, 2, 0]])

In [40]:
np.concatenate([a,b],axis=0)

array([[1, 2, 3],
       [1, 2, 5],
       [3, 3, 4],
       [1, 2, 0]])

In [41]:
np.ndim(b)

2

In [43]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([0.0,1.0,2.0])  
   
print ('First array:\n',a )
print ('Second array:\n',b )
print ("\n")   
print ('First Array + Second Array=\n',a+b)

First array:
 [[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
Second array:
 [0. 1. 2.]


First Array + Second Array=
 [[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]
 [30. 31. 32.]]


### file input output

In [44]:
a = np.array([11,2,30,4,5,13]) 
np.save('dar',a)

In [45]:
# To reconstruct array from demofile.npy, use load() function.
b = np.load('dar.npy') 
print (b)

[11  2 30  4  5 13]


In [46]:
np.random.randint(2,10,(3,4))

array([[7, 2, 5, 3],
       [9, 4, 2, 6],
       [7, 7, 8, 4]])

In [48]:
np.random.randint(2,3.8,(3,3))

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [49]:
np.random.randint(2,50, (2,3,4) )

array([[[49, 35, 47, 35],
        [28, 10, 34,  2],
        [ 8, 38, 15,  7]],

       [[28, 39, 43, 46],
        [46,  2,  4, 24],
        [19, 31, 41, 25]]])

In [50]:
np.random.rand(5,4)

array([[0.09882442, 0.06163918, 0.6390256 , 0.43359111],
       [0.50670503, 0.47410942, 0.51277825, 0.41703965],
       [0.9701602 , 0.83647351, 0.77244062, 0.18090565],
       [0.8219337 , 0.42881703, 0.66077872, 0.95288988],
       [0.68257404, 0.16592385, 0.85462807, 0.91208757]])

In [51]:
a =np.random.randn(4,4)

In [52]:
a

array([[-0.68193743,  0.98487483,  0.92990775,  1.14492212],
       [ 1.00413695, -1.59540662,  0.74567706,  0.97414941],
       [-1.15225493, -0.80853556, -1.47231   , -0.10208243],
       [ 0.81825794, -0.8430383 , -0.44330399,  0.78138689]])

In [53]:
a.reshape(2,8)

array([[-0.68193743,  0.98487483,  0.92990775,  1.14492212,  1.00413695,
        -1.59540662,  0.74567706,  0.97414941],
       [-1.15225493, -0.80853556, -1.47231   , -0.10208243,  0.81825794,
        -0.8430383 , -0.44330399,  0.78138689]])

In [56]:
np.random.randn(5,2)

array([[ 0.61860231,  1.02192929],
       [-0.47521702, -1.30163794],
       [ 1.31010373,  1.64667513],
       [ 0.3473535 , -0.61791652],
       [ 0.37290561, -0.69166786]])

In [57]:
a6 = np.random.randint(0,3 , (3,3))

In [58]:
a7 = np.random.randint(0,3 , (3,3))

In [60]:
a6

array([[2, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [61]:
a7

array([[1, 0, 0],
       [1, 1, 2],
       [2, 0, 1]])

In [59]:
a6*a7

array([[2, 0, 0],
       [0, 0, 4],
       [0, 0, 0]])

In [62]:
a6@a7

array([[3, 1, 2],
       [4, 0, 2],
       [0, 0, 0]])

In [63]:
a6

array([[2, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [64]:
a7

array([[1, 0, 0],
       [1, 1, 2],
       [2, 0, 1]])

In [65]:
(2*1)+(1*1)+(0*2)

3

In [66]:
(2*0)+(1*1)+(0*0)

1

In [67]:
a6**3

array([[8, 1, 0],
       [0, 0, 8],
       [0, 0, 0]], dtype=int32)